# Generated by Django 2.0.1 on 2018-01-13 21:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bot', '0002_auto_20180114_0235'),
    ]

    operations = [
        migrations.AddField(
            model_name='chat',
            name='isUserCreated',
            field=models.BooleanField(default=True),
            preserve_default=False,
        ),
    ]
